language: python
python:
  - "3.4"
addons:
  postgresql: "9.3"
install:
  - pip install wheel
  - pip install -r requirements.txt
  - pip install -r requirements-testing.txt
  - npm install
before_script:
  - createdb -U postgres pastry
  - python manage.py migrate --noinput
  - python manage.py createsuperuser --username=travis --email=travis@localhost --noinput
script:
  - make dist
  - tox
notifications:
  irc:
    - "chat.freenode.net#szulabs"
deploy:
  provider: releases
  file:
    - dist/pastry-*.tar.gz
    - dist/pastry-*.whl
  file_glob: true
  on:
    repo: szulabs/pastry
    tags: true
    all_branches: true
  api_key:
    secure: QCCN9cooxjwTvXVLrjwZQWBkMhJ1Py07G/4tjNxa0AJNEK3hl4ZtCoDXB54QYVD6JNMpghojEAa6fLAN2gnhnHzcTmDHXMlKGtLnJSipPT17EVtR8Oh8rRbvpRA/d/Sq6uexBfT+uXru7hOM+B940CibMaeTwelBk8a2AY4Rk+w=
